# Generated by Django 5.2 on 2025-04-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
