# Generated by Django 5.2 on 2025-04-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_verified_merchant_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='profile',
        ),
    ]
