# Generated by Django 5.2 on 2025-04-10 05:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_discountevent_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesGroup',
            new_name='CategoryGroup',
        ),
    ]
