# Generated by Django 5.2 on 2025-04-10 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_categoriesgroup_categorygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorygroup',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='category_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categorygroup'),
        ),
    ]
